*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZHR_PRT_V007....................................*
FORM GET_DATA_ZHR_PRT_V007.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHR_PRT_T007 WHERE
(VIM_WHERETAB) .
    CLEAR ZHR_PRT_V007 .
ZHR_PRT_V007-MANDT =
ZHR_PRT_T007-MANDT .
ZHR_PRT_V007-AWART =
ZHR_PRT_T007-AWART .
ZHR_PRT_V007-MAXDY =
ZHR_PRT_T007-MAXDY .
    SELECT * FROM T554S WHERE
SUBTY = ZHR_PRT_T007-AWART .
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHR_PRT_V007-ATEXT =
T554T-ATEXT .
      ENDIF.
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZHR_PRT_V007.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHR_PRT_V007 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHR_PRT_V007.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHR_PRT_V007-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_T007 WHERE
  AWART = ZHR_PRT_V007-AWART .
    IF SY-SUBRC = 0.
    DELETE ZHR_PRT_T007 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_T007 WHERE
  AWART = ZHR_PRT_V007-AWART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHR_PRT_T007.
    ENDIF.
ZHR_PRT_T007-MANDT =
ZHR_PRT_V007-MANDT .
ZHR_PRT_T007-AWART =
ZHR_PRT_V007-AWART .
ZHR_PRT_T007-MAXDY =
ZHR_PRT_V007-MAXDY .
    IF SY-SUBRC = 0.
    UPDATE ZHR_PRT_T007 ##WARN_OK.
    ELSE.
    INSERT ZHR_PRT_T007 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHR_PRT_V007-UPD_FLAG,
STATUS_ZHR_PRT_V007-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHR_PRT_V007.
  SELECT SINGLE * FROM ZHR_PRT_T007 WHERE
AWART = ZHR_PRT_V007-AWART .
ZHR_PRT_V007-MANDT =
ZHR_PRT_T007-MANDT .
ZHR_PRT_V007-AWART =
ZHR_PRT_T007-AWART .
ZHR_PRT_V007-MAXDY =
ZHR_PRT_T007-MAXDY .
    SELECT * FROM T554S WHERE
SUBTY = ZHR_PRT_T007-AWART .
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHR_PRT_V007-ATEXT =
T554T-ATEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHR_PRT_V007-ATEXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_V007-ATEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHR_PRT_V007 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHR_PRT_V007-AWART TO
ZHR_PRT_T007-AWART .
MOVE ZHR_PRT_V007-MANDT TO
ZHR_PRT_T007-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHR_PRT_T007'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHR_PRT_T007 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHR_PRT_T007'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHR_PRT_V007 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHR_PRT_T007-MANDT =
ZHR_PRT_V007-MANDT .
ZHR_PRT_T007-AWART =
ZHR_PRT_V007-AWART .
ZHR_PRT_T007-MAXDY =
ZHR_PRT_V007-MAXDY .
    SELECT * FROM T554S WHERE
SUBTY = ZHR_PRT_T007-AWART .
      SELECT SINGLE * FROM T554T WHERE
MOABW = T554S-MOABW AND
AWART = T554S-SUBTY AND
SPRSL = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZHR_PRT_V007-ATEXT =
T554T-ATEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZHR_PRT_V007-ATEXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_V007-ATEXT .
    ENDIF.
ENDFORM.
*...processing: ZHR_PRT_V008....................................*
FORM GET_DATA_ZHR_PRT_V008.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHR_PRT_T008 WHERE
(VIM_WHERETAB) .
    CLEAR ZHR_PRT_V008 .
ZHR_PRT_V008-MANDT =
ZHR_PRT_T008-MANDT .
ZHR_PRT_V008-APTYP =
ZHR_PRT_T008-APTYP .
ZHR_PRT_V008-HEAD =
ZHR_PRT_T008-HEAD .
ZHR_PRT_V008-ZZROL =
ZHR_PRT_T008-ZZROL .
    SELECT SINGLE * FROM ZHR_PRT_TROLL WHERE
APTYP = ZHR_PRT_T008-APTYP AND
HEAD = ZHR_PRT_T008-HEAD .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = ZHR_PRT_V008.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHR_PRT_V008 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHR_PRT_V008.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHR_PRT_V008-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_T008 WHERE
  APTYP = ZHR_PRT_V008-APTYP AND
  HEAD = ZHR_PRT_V008-HEAD AND
  ZZROL = ZHR_PRT_V008-ZZROL .
    IF SY-SUBRC = 0.
    DELETE ZHR_PRT_T008 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_T008 WHERE
  APTYP = ZHR_PRT_V008-APTYP AND
  HEAD = ZHR_PRT_V008-HEAD AND
  ZZROL = ZHR_PRT_V008-ZZROL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHR_PRT_T008.
    ENDIF.
ZHR_PRT_T008-MANDT =
ZHR_PRT_V008-MANDT .
ZHR_PRT_T008-APTYP =
ZHR_PRT_V008-APTYP .
ZHR_PRT_T008-HEAD =
ZHR_PRT_V008-HEAD .
ZHR_PRT_T008-ZZROL =
ZHR_PRT_V008-ZZROL .
    IF SY-SUBRC = 0.
    UPDATE ZHR_PRT_T008 ##WARN_OK.
    ELSE.
    INSERT ZHR_PRT_T008 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHR_PRT_V008-UPD_FLAG,
STATUS_ZHR_PRT_V008-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHR_PRT_V008.
  SELECT SINGLE * FROM ZHR_PRT_T008 WHERE
APTYP = ZHR_PRT_V008-APTYP AND
HEAD = ZHR_PRT_V008-HEAD AND
ZZROL = ZHR_PRT_V008-ZZROL .
ZHR_PRT_V008-MANDT =
ZHR_PRT_T008-MANDT .
ZHR_PRT_V008-APTYP =
ZHR_PRT_T008-APTYP .
ZHR_PRT_V008-HEAD =
ZHR_PRT_T008-HEAD .
ZHR_PRT_V008-ZZROL =
ZHR_PRT_T008-ZZROL .
    SELECT SINGLE * FROM ZHR_PRT_TROLL WHERE
APTYP = ZHR_PRT_T008-APTYP AND
HEAD = ZHR_PRT_T008-HEAD .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHR_PRT_V008 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHR_PRT_V008-APTYP TO
ZHR_PRT_T008-APTYP .
MOVE ZHR_PRT_V008-HEAD TO
ZHR_PRT_T008-HEAD .
MOVE ZHR_PRT_V008-ZZROL TO
ZHR_PRT_T008-ZZROL .
MOVE ZHR_PRT_V008-MANDT TO
ZHR_PRT_T008-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHR_PRT_T008'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHR_PRT_T008 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHR_PRT_T008'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHR_PRT_V008 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHR_PRT_T008-MANDT =
ZHR_PRT_V008-MANDT .
ZHR_PRT_T008-APTYP =
ZHR_PRT_V008-APTYP .
ZHR_PRT_T008-HEAD =
ZHR_PRT_V008-HEAD .
ZHR_PRT_T008-ZZROL =
ZHR_PRT_V008-ZZROL .
    SELECT SINGLE * FROM ZHR_PRT_TROLL WHERE
APTYP = ZHR_PRT_T008-APTYP AND
HEAD = ZHR_PRT_T008-HEAD .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*...processing: ZHR_PRT_V010....................................*
FORM GET_DATA_ZHR_PRT_V010.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHR_PRT_T010 WHERE
(VIM_WHERETAB) .
    CLEAR ZHR_PRT_V010 .
ZHR_PRT_V010-MANDT =
ZHR_PRT_T010-MANDT .
ZHR_PRT_V010-SRCID =
ZHR_PRT_T010-SRCID .
ZHR_PRT_V010-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_V010-ACTIV =
ZHR_PRT_T010-ACTIV .
ZHR_PRT_V010-NRNR =
ZHR_PRT_T010-NRNR .
<VIM_TOTAL_STRUC> = ZHR_PRT_V010.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHR_PRT_V010 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHR_PRT_V010.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHR_PRT_V010-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_T010 WHERE
  SRCID = ZHR_PRT_V010-SRCID .
    IF SY-SUBRC = 0.
    DELETE ZHR_PRT_T010 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_T010 WHERE
  SRCID = ZHR_PRT_V010-SRCID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHR_PRT_T010.
    ENDIF.
ZHR_PRT_T010-MANDT =
ZHR_PRT_V010-MANDT .
ZHR_PRT_T010-SRCID =
ZHR_PRT_V010-SRCID .
ZHR_PRT_T010-SRCID_T =
ZHR_PRT_V010-SRCID_T .
ZHR_PRT_T010-ACTIV =
ZHR_PRT_V010-ACTIV .
ZHR_PRT_T010-NRNR =
ZHR_PRT_V010-NRNR .
    IF SY-SUBRC = 0.
    UPDATE ZHR_PRT_T010 ##WARN_OK.
    ELSE.
    INSERT ZHR_PRT_T010 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHR_PRT_V010-UPD_FLAG,
STATUS_ZHR_PRT_V010-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHR_PRT_V010.
  SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_V010-SRCID .
ZHR_PRT_V010-MANDT =
ZHR_PRT_T010-MANDT .
ZHR_PRT_V010-SRCID =
ZHR_PRT_T010-SRCID .
ZHR_PRT_V010-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_V010-ACTIV =
ZHR_PRT_T010-ACTIV .
ZHR_PRT_V010-NRNR =
ZHR_PRT_T010-NRNR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHR_PRT_V010 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHR_PRT_V010-SRCID TO
ZHR_PRT_T010-SRCID .
MOVE ZHR_PRT_V010-MANDT TO
ZHR_PRT_T010-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHR_PRT_T010'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHR_PRT_T010 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHR_PRT_T010'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZHR_PRT_VADMIN..................................*
FORM GET_DATA_ZHR_PRT_VADMIN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHR_PRT_TADMIN WHERE
(VIM_WHERETAB) .
    CLEAR ZHR_PRT_VADMIN .
ZHR_PRT_VADMIN-MANDT =
ZHR_PRT_TADMIN-MANDT .
ZHR_PRT_VADMIN-SRCID =
ZHR_PRT_TADMIN-SRCID .
ZHR_PRT_VADMIN-SEQNR =
ZHR_PRT_TADMIN-SEQNR .
ZHR_PRT_VADMIN-PERNR =
ZHR_PRT_TADMIN-PERNR .
    SELECT * FROM PA0001 WHERE
PERNR = ZHR_PRT_TADMIN-PERNR .
ZHR_PRT_VADMIN-ENAME =
PA0001-ENAME .
      EXIT.
    ENDSELECT.
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TADMIN-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VADMIN-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VADMIN-ACTIV =
ZHR_PRT_T010-ACTIV .
    ENDIF.
<VIM_TOTAL_STRUC> = ZHR_PRT_VADMIN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHR_PRT_VADMIN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHR_PRT_VADMIN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHR_PRT_VADMIN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_TADMIN WHERE
  SRCID = ZHR_PRT_VADMIN-SRCID AND
  SEQNR = ZHR_PRT_VADMIN-SEQNR .
    IF SY-SUBRC = 0.
    DELETE ZHR_PRT_TADMIN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_TADMIN WHERE
  SRCID = ZHR_PRT_VADMIN-SRCID AND
  SEQNR = ZHR_PRT_VADMIN-SEQNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHR_PRT_TADMIN.
    ENDIF.
ZHR_PRT_TADMIN-MANDT =
ZHR_PRT_VADMIN-MANDT .
ZHR_PRT_TADMIN-SRCID =
ZHR_PRT_VADMIN-SRCID .
ZHR_PRT_TADMIN-SEQNR =
ZHR_PRT_VADMIN-SEQNR .
ZHR_PRT_TADMIN-PERNR =
ZHR_PRT_VADMIN-PERNR .
    IF SY-SUBRC = 0.
    UPDATE ZHR_PRT_TADMIN ##WARN_OK.
    ELSE.
    INSERT ZHR_PRT_TADMIN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHR_PRT_VADMIN-UPD_FLAG,
STATUS_ZHR_PRT_VADMIN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHR_PRT_VADMIN.
  SELECT SINGLE * FROM ZHR_PRT_TADMIN WHERE
SRCID = ZHR_PRT_VADMIN-SRCID AND
SEQNR = ZHR_PRT_VADMIN-SEQNR .
ZHR_PRT_VADMIN-MANDT =
ZHR_PRT_TADMIN-MANDT .
ZHR_PRT_VADMIN-SRCID =
ZHR_PRT_TADMIN-SRCID .
ZHR_PRT_VADMIN-SEQNR =
ZHR_PRT_TADMIN-SEQNR .
ZHR_PRT_VADMIN-PERNR =
ZHR_PRT_TADMIN-PERNR .
    SELECT * FROM PA0001 WHERE
PERNR = ZHR_PRT_TADMIN-PERNR .
ZHR_PRT_VADMIN-ENAME =
PA0001-ENAME .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VADMIN-ENAME .
    ENDIF.
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TADMIN-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VADMIN-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VADMIN-ACTIV =
ZHR_PRT_T010-ACTIV .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VADMIN-SRCID_T .
      CLEAR ZHR_PRT_VADMIN-ACTIV .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHR_PRT_VADMIN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHR_PRT_VADMIN-SRCID TO
ZHR_PRT_TADMIN-SRCID .
MOVE ZHR_PRT_VADMIN-SEQNR TO
ZHR_PRT_TADMIN-SEQNR .
MOVE ZHR_PRT_VADMIN-MANDT TO
ZHR_PRT_TADMIN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHR_PRT_TADMIN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHR_PRT_TADMIN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHR_PRT_TADMIN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHR_PRT_VADMIN USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHR_PRT_TADMIN-MANDT =
ZHR_PRT_VADMIN-MANDT .
ZHR_PRT_TADMIN-SRCID =
ZHR_PRT_VADMIN-SRCID .
ZHR_PRT_TADMIN-SEQNR =
ZHR_PRT_VADMIN-SEQNR .
ZHR_PRT_TADMIN-PERNR =
ZHR_PRT_VADMIN-PERNR .
    SELECT * FROM PA0001 WHERE
PERNR = ZHR_PRT_TADMIN-PERNR .
ZHR_PRT_VADMIN-ENAME =
PA0001-ENAME .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VADMIN-ENAME .
    ENDIF.
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TADMIN-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VADMIN-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VADMIN-ACTIV =
ZHR_PRT_T010-ACTIV .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VADMIN-SRCID_T .
      CLEAR ZHR_PRT_VADMIN-ACTIV .
    ENDIF.
ENDFORM.
*...processing: ZHR_PRT_VONAYCI.................................*
FORM GET_DATA_ZHR_PRT_VONAYCI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHR_PRT_TONAYCI WHERE
(VIM_WHERETAB) .
    CLEAR ZHR_PRT_VONAYCI .
ZHR_PRT_VONAYCI-MANDT =
ZHR_PRT_TONAYCI-MANDT .
ZHR_PRT_VONAYCI-SRCID =
ZHR_PRT_TONAYCI-SRCID .
ZHR_PRT_VONAYCI-PERNR =
ZHR_PRT_TONAYCI-PERNR .
ZHR_PRT_VONAYCI-ZAPP1 =
ZHR_PRT_TONAYCI-ZAPP1 .
ZHR_PRT_VONAYCI-ZAPP2 =
ZHR_PRT_TONAYCI-ZAPP2 .
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TONAYCI-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VONAYCI-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VONAYCI-ACTIV =
ZHR_PRT_T010-ACTIV .
    ENDIF.
    SELECT * FROM PA0001 WHERE
PERNR = ZHR_PRT_TONAYCI-PERNR .
ZHR_PRT_VONAYCI-ENAME =
PA0001-ENAME .
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZHR_PRT_VONAYCI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHR_PRT_VONAYCI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHR_PRT_VONAYCI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHR_PRT_VONAYCI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_TONAYCI WHERE
  SRCID = ZHR_PRT_VONAYCI-SRCID AND
  PERNR = ZHR_PRT_VONAYCI-PERNR .
    IF SY-SUBRC = 0.
    DELETE ZHR_PRT_TONAYCI .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_TONAYCI WHERE
  SRCID = ZHR_PRT_VONAYCI-SRCID AND
  PERNR = ZHR_PRT_VONAYCI-PERNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHR_PRT_TONAYCI.
    ENDIF.
ZHR_PRT_TONAYCI-MANDT =
ZHR_PRT_VONAYCI-MANDT .
ZHR_PRT_TONAYCI-SRCID =
ZHR_PRT_VONAYCI-SRCID .
ZHR_PRT_TONAYCI-PERNR =
ZHR_PRT_VONAYCI-PERNR .
ZHR_PRT_TONAYCI-ZAPP1 =
ZHR_PRT_VONAYCI-ZAPP1 .
ZHR_PRT_TONAYCI-ZAPP2 =
ZHR_PRT_VONAYCI-ZAPP2 .
    IF SY-SUBRC = 0.
    UPDATE ZHR_PRT_TONAYCI ##WARN_OK.
    ELSE.
    INSERT ZHR_PRT_TONAYCI .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHR_PRT_VONAYCI-UPD_FLAG,
STATUS_ZHR_PRT_VONAYCI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHR_PRT_VONAYCI.
  SELECT SINGLE * FROM ZHR_PRT_TONAYCI WHERE
SRCID = ZHR_PRT_VONAYCI-SRCID AND
PERNR = ZHR_PRT_VONAYCI-PERNR .
ZHR_PRT_VONAYCI-MANDT =
ZHR_PRT_TONAYCI-MANDT .
ZHR_PRT_VONAYCI-SRCID =
ZHR_PRT_TONAYCI-SRCID .
ZHR_PRT_VONAYCI-PERNR =
ZHR_PRT_TONAYCI-PERNR .
ZHR_PRT_VONAYCI-ZAPP1 =
ZHR_PRT_TONAYCI-ZAPP1 .
ZHR_PRT_VONAYCI-ZAPP2 =
ZHR_PRT_TONAYCI-ZAPP2 .
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TONAYCI-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VONAYCI-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VONAYCI-ACTIV =
ZHR_PRT_T010-ACTIV .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VONAYCI-SRCID_T .
      CLEAR ZHR_PRT_VONAYCI-ACTIV .
    ENDIF.
    SELECT * FROM PA0001 WHERE
PERNR = ZHR_PRT_TONAYCI-PERNR .
ZHR_PRT_VONAYCI-ENAME =
PA0001-ENAME .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VONAYCI-ENAME .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHR_PRT_VONAYCI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHR_PRT_VONAYCI-SRCID TO
ZHR_PRT_TONAYCI-SRCID .
MOVE ZHR_PRT_VONAYCI-PERNR TO
ZHR_PRT_TONAYCI-PERNR .
MOVE ZHR_PRT_VONAYCI-MANDT TO
ZHR_PRT_TONAYCI-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHR_PRT_TONAYCI'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHR_PRT_TONAYCI TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHR_PRT_TONAYCI'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHR_PRT_VONAYCI USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHR_PRT_TONAYCI-MANDT =
ZHR_PRT_VONAYCI-MANDT .
ZHR_PRT_TONAYCI-SRCID =
ZHR_PRT_VONAYCI-SRCID .
ZHR_PRT_TONAYCI-PERNR =
ZHR_PRT_VONAYCI-PERNR .
ZHR_PRT_TONAYCI-ZAPP1 =
ZHR_PRT_VONAYCI-ZAPP1 .
ZHR_PRT_TONAYCI-ZAPP2 =
ZHR_PRT_VONAYCI-ZAPP2 .
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TONAYCI-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VONAYCI-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VONAYCI-ACTIV =
ZHR_PRT_T010-ACTIV .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VONAYCI-SRCID_T .
      CLEAR ZHR_PRT_VONAYCI-ACTIV .
    ENDIF.
    SELECT * FROM PA0001 WHERE
PERNR = ZHR_PRT_TONAYCI-PERNR .
ZHR_PRT_VONAYCI-ENAME =
PA0001-ENAME .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VONAYCI-ENAME .
    ENDIF.
ENDFORM.
*...processing: ZHR_PRT_VONYIK..................................*
FORM GET_DATA_ZHR_PRT_VONYIK.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHR_PRT_TONYIK WHERE
(VIM_WHERETAB) .
    CLEAR ZHR_PRT_VONYIK .
ZHR_PRT_VONYIK-MANDT =
ZHR_PRT_TONYIK-MANDT .
ZHR_PRT_VONYIK-SRCID =
ZHR_PRT_TONYIK-SRCID .
ZHR_PRT_VONYIK-ORGSVY =
ZHR_PRT_TONYIK-ORGSVY .
ZHR_PRT_VONYIK-SEQNR =
ZHR_PRT_TONYIK-SEQNR .
ZHR_PRT_VONYIK-PLANS =
ZHR_PRT_TONYIK-PLANS .
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TONYIK-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VONYIK-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VONYIK-ACTIV =
ZHR_PRT_T010-ACTIV .
    ENDIF.
    SELECT * FROM HRP1000 WHERE
PLVAR = '01' AND
OTYPE = 'S' AND
OBJID = ZHR_PRT_TONYIK-PLANS AND
LANGU = SYST-LANGU .
ZHR_PRT_VONYIK-STEXT =
HRP1000-STEXT .
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZHR_PRT_VONYIK.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHR_PRT_VONYIK .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHR_PRT_VONYIK.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHR_PRT_VONYIK-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_TONYIK WHERE
  SRCID = ZHR_PRT_VONYIK-SRCID AND
  ORGSVY = ZHR_PRT_VONYIK-ORGSVY AND
  SEQNR = ZHR_PRT_VONYIK-SEQNR AND
  PLANS = ZHR_PRT_VONYIK-PLANS .
    IF SY-SUBRC = 0.
    DELETE ZHR_PRT_TONYIK .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_TONYIK WHERE
  SRCID = ZHR_PRT_VONYIK-SRCID AND
  ORGSVY = ZHR_PRT_VONYIK-ORGSVY AND
  SEQNR = ZHR_PRT_VONYIK-SEQNR AND
  PLANS = ZHR_PRT_VONYIK-PLANS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHR_PRT_TONYIK.
    ENDIF.
ZHR_PRT_TONYIK-MANDT =
ZHR_PRT_VONYIK-MANDT .
ZHR_PRT_TONYIK-SRCID =
ZHR_PRT_VONYIK-SRCID .
ZHR_PRT_TONYIK-ORGSVY =
ZHR_PRT_VONYIK-ORGSVY .
ZHR_PRT_TONYIK-SEQNR =
ZHR_PRT_VONYIK-SEQNR .
ZHR_PRT_TONYIK-PLANS =
ZHR_PRT_VONYIK-PLANS .
    IF SY-SUBRC = 0.
    UPDATE ZHR_PRT_TONYIK ##WARN_OK.
    ELSE.
    INSERT ZHR_PRT_TONYIK .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHR_PRT_VONYIK-UPD_FLAG,
STATUS_ZHR_PRT_VONYIK-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHR_PRT_VONYIK.
  SELECT SINGLE * FROM ZHR_PRT_TONYIK WHERE
SRCID = ZHR_PRT_VONYIK-SRCID AND
ORGSVY = ZHR_PRT_VONYIK-ORGSVY AND
SEQNR = ZHR_PRT_VONYIK-SEQNR AND
PLANS = ZHR_PRT_VONYIK-PLANS .
ZHR_PRT_VONYIK-MANDT =
ZHR_PRT_TONYIK-MANDT .
ZHR_PRT_VONYIK-SRCID =
ZHR_PRT_TONYIK-SRCID .
ZHR_PRT_VONYIK-ORGSVY =
ZHR_PRT_TONYIK-ORGSVY .
ZHR_PRT_VONYIK-SEQNR =
ZHR_PRT_TONYIK-SEQNR .
ZHR_PRT_VONYIK-PLANS =
ZHR_PRT_TONYIK-PLANS .
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TONYIK-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VONYIK-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VONYIK-ACTIV =
ZHR_PRT_T010-ACTIV .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VONYIK-SRCID_T .
      CLEAR ZHR_PRT_VONYIK-ACTIV .
    ENDIF.
    SELECT * FROM HRP1000 WHERE
PLVAR = '01' AND
OTYPE = 'S' AND
OBJID = ZHR_PRT_TONYIK-PLANS AND
LANGU = SYST-LANGU .
ZHR_PRT_VONYIK-STEXT =
HRP1000-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VONYIK-STEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHR_PRT_VONYIK USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHR_PRT_VONYIK-SRCID TO
ZHR_PRT_TONYIK-SRCID .
MOVE ZHR_PRT_VONYIK-ORGSVY TO
ZHR_PRT_TONYIK-ORGSVY .
MOVE ZHR_PRT_VONYIK-SEQNR TO
ZHR_PRT_TONYIK-SEQNR .
MOVE ZHR_PRT_VONYIK-PLANS TO
ZHR_PRT_TONYIK-PLANS .
MOVE ZHR_PRT_VONYIK-MANDT TO
ZHR_PRT_TONYIK-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHR_PRT_TONYIK'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHR_PRT_TONYIK TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHR_PRT_TONYIK'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHR_PRT_VONYIK USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHR_PRT_TONYIK-MANDT =
ZHR_PRT_VONYIK-MANDT .
ZHR_PRT_TONYIK-SRCID =
ZHR_PRT_VONYIK-SRCID .
ZHR_PRT_TONYIK-ORGSVY =
ZHR_PRT_VONYIK-ORGSVY .
ZHR_PRT_TONYIK-SEQNR =
ZHR_PRT_VONYIK-SEQNR .
ZHR_PRT_TONYIK-PLANS =
ZHR_PRT_VONYIK-PLANS .
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TONYIK-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VONYIK-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VONYIK-ACTIV =
ZHR_PRT_T010-ACTIV .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VONYIK-SRCID_T .
      CLEAR ZHR_PRT_VONYIK-ACTIV .
    ENDIF.
    SELECT * FROM HRP1000 WHERE
PLVAR = '01' AND
OTYPE = 'S' AND
OBJID = ZHR_PRT_TONYIK-PLANS AND
LANGU = SYST-LANGU .
ZHR_PRT_VONYIK-STEXT =
HRP1000-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VONYIK-STEXT .
    ENDIF.
ENDFORM.
*...processing: ZHR_PRT_VSTELL..................................*
FORM GET_DATA_ZHR_PRT_VSTELL.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZHR_PRT_TSTELL WHERE
(VIM_WHERETAB) .
    CLEAR ZHR_PRT_VSTELL .
ZHR_PRT_VSTELL-MANDT =
ZHR_PRT_TSTELL-MANDT .
ZHR_PRT_VSTELL-SRCID =
ZHR_PRT_TSTELL-SRCID .
ZHR_PRT_VSTELL-APTYP =
ZHR_PRT_TSTELL-APTYP .
ZHR_PRT_VSTELL-STELL =
ZHR_PRT_TSTELL-STELL .
    SELECT * FROM HRP1000 WHERE
PLVAR = '01' AND
OTYPE = 'C' AND
OBJID = ZHR_PRT_TSTELL-STELL AND
LANGU = SYST-LANGU .
ZHR_PRT_VSTELL-STEXT =
HRP1000-STEXT .
      EXIT.
    ENDSELECT.
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TSTELL-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VSTELL-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VSTELL-ACTIV =
ZHR_PRT_T010-ACTIV .
    ENDIF.
<VIM_TOTAL_STRUC> = ZHR_PRT_VSTELL.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZHR_PRT_VSTELL .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZHR_PRT_VSTELL.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZHR_PRT_VSTELL-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_TSTELL WHERE
  SRCID = ZHR_PRT_VSTELL-SRCID AND
  APTYP = ZHR_PRT_VSTELL-APTYP AND
  STELL = ZHR_PRT_VSTELL-STELL .
    IF SY-SUBRC = 0.
    DELETE ZHR_PRT_TSTELL .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZHR_PRT_TSTELL WHERE
  SRCID = ZHR_PRT_VSTELL-SRCID AND
  APTYP = ZHR_PRT_VSTELL-APTYP AND
  STELL = ZHR_PRT_VSTELL-STELL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZHR_PRT_TSTELL.
    ENDIF.
ZHR_PRT_TSTELL-MANDT =
ZHR_PRT_VSTELL-MANDT .
ZHR_PRT_TSTELL-SRCID =
ZHR_PRT_VSTELL-SRCID .
ZHR_PRT_TSTELL-APTYP =
ZHR_PRT_VSTELL-APTYP .
ZHR_PRT_TSTELL-STELL =
ZHR_PRT_VSTELL-STELL .
    IF SY-SUBRC = 0.
    UPDATE ZHR_PRT_TSTELL ##WARN_OK.
    ELSE.
    INSERT ZHR_PRT_TSTELL .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZHR_PRT_VSTELL-UPD_FLAG,
STATUS_ZHR_PRT_VSTELL-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZHR_PRT_VSTELL.
  SELECT SINGLE * FROM ZHR_PRT_TSTELL WHERE
SRCID = ZHR_PRT_VSTELL-SRCID AND
APTYP = ZHR_PRT_VSTELL-APTYP AND
STELL = ZHR_PRT_VSTELL-STELL .
ZHR_PRT_VSTELL-MANDT =
ZHR_PRT_TSTELL-MANDT .
ZHR_PRT_VSTELL-SRCID =
ZHR_PRT_TSTELL-SRCID .
ZHR_PRT_VSTELL-APTYP =
ZHR_PRT_TSTELL-APTYP .
ZHR_PRT_VSTELL-STELL =
ZHR_PRT_TSTELL-STELL .
    SELECT * FROM HRP1000 WHERE
PLVAR = '01' AND
OTYPE = 'C' AND
OBJID = ZHR_PRT_TSTELL-STELL AND
LANGU = SYST-LANGU .
ZHR_PRT_VSTELL-STEXT =
HRP1000-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VSTELL-STEXT .
    ENDIF.
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TSTELL-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VSTELL-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VSTELL-ACTIV =
ZHR_PRT_T010-ACTIV .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VSTELL-SRCID_T .
      CLEAR ZHR_PRT_VSTELL-ACTIV .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZHR_PRT_VSTELL USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZHR_PRT_VSTELL-SRCID TO
ZHR_PRT_TSTELL-SRCID .
MOVE ZHR_PRT_VSTELL-APTYP TO
ZHR_PRT_TSTELL-APTYP .
MOVE ZHR_PRT_VSTELL-STELL TO
ZHR_PRT_TSTELL-STELL .
MOVE ZHR_PRT_VSTELL-MANDT TO
ZHR_PRT_TSTELL-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZHR_PRT_TSTELL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZHR_PRT_TSTELL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZHR_PRT_TSTELL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZHR_PRT_VSTELL USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZHR_PRT_TSTELL-MANDT =
ZHR_PRT_VSTELL-MANDT .
ZHR_PRT_TSTELL-SRCID =
ZHR_PRT_VSTELL-SRCID .
ZHR_PRT_TSTELL-APTYP =
ZHR_PRT_VSTELL-APTYP .
ZHR_PRT_TSTELL-STELL =
ZHR_PRT_VSTELL-STELL .
    SELECT * FROM HRP1000 WHERE
PLVAR = '01' AND
OTYPE = 'C' AND
OBJID = ZHR_PRT_TSTELL-STELL AND
LANGU = SYST-LANGU .
ZHR_PRT_VSTELL-STEXT =
HRP1000-STEXT .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VSTELL-STEXT .
    ENDIF.
    SELECT SINGLE * FROM ZHR_PRT_T010 WHERE
SRCID = ZHR_PRT_TSTELL-SRCID .
    IF SY-SUBRC EQ 0.
ZHR_PRT_VSTELL-SRCID_T =
ZHR_PRT_T010-SRCID_T .
ZHR_PRT_VSTELL-ACTIV =
ZHR_PRT_T010-ACTIV .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZHR_PRT_VSTELL-SRCID_T .
      CLEAR ZHR_PRT_VSTELL-ACTIV .
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
